name: ebchat
description: EBchat widget
version: 0.1.0+1
homepage: https://ebchat-saas.e-butler.com/
repository: https://github.com/EButler-QA/ebchat-mobile-flutter-sdk
issue_tracker: https://github.com/EButler-QA/ebchat-mobile-flutter-sdk/issues

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  characters: ^1.1.0
  chewie: ^1.2.0
  collection: ^1.15.0
  diacritic: ^0.1.3
  dio: ^4.0.0
  ezanimation: ^0.6.0
  file_picker: ^5.0.0
  flutter_markdown: ^0.6.1
  flutter_portal: ^1.0.0
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.0.1
  http_parser: ^4.0.0
  image_gallery_saver: ^1.7.0
  image_picker: ^0.8.2
  lottie: ^1.0.1
  meta: ^1.3.0
  path_provider: ^2.0.1
  photo_view: ^0.14.0
  rxdart: ^0.27.0
  share_plus: ^4.0.1
  shimmer: ^2.0.0
  substring_highlight: ^1.0.26
  synchronized: ^3.0.0
  url_launcher: ^6.0.3
  video_player: ^2.1.0
  video_thumbnail: ^0.5.0
  visibility_detector: ^0.3.3
  cached_network_image: ^3.1.0
  google_fonts: ^3.0.1
  jiffy: ^5.0.0
  logger: ^1.1.0
  stream_chat_flutter_core: ^4.6.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  stream_chat: ^4.6.0
  stream_chat_flutter: ^4.6.0
  provider: ^6.0.3
  emoji_picker_flutter: ^1.0.8
  record: ^4.4.0
  just_audio: ^0.9.18
  location: ^4.4.0
  flutter_map: ^2.2.0
  latlong2: ^0.8.1
  sound_mode: ^2.0.2
  photo_manager: ^2.0.0
  flutter:
    sdk: flutter
  video_compress: ^3.1.1
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
